apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: tanuu
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: setup/argo-config
    repoURL: https://github.com/tanuuidp/tanuu.git
    targetRevision: templateSandbox_daniel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true